"""Build six fully rendered, dependency-free language pages."""
from pathlib import Path
from html import escape as esc
import json

ROOT = Path(__file__).parent
PUBLIC = ROOT / 'public'
LANGS = [('en','English'),('es','Español'),('pt','Português'),('fr','Français'),('de','Deutsch'),('it','Italiano')]
SOCIALS = [('Instagram','https://www.instagram.com/fame.agents/'),('Facebook','https://www.facebook.com/share/1DbkapWbQA/?mibextid=wwXIfr'),('TikTok','https://www.tiktok.com/@fame_agents'),('YouTube','https://youtube.com/@fameagents'),('LinkedIn','https://www.linkedin.com/company/fame-agents/'),('X','https://x.com/fame_agents')]

# Each service: name, outcome, full deliverables. Keep the eight groups in order.
SERVICES = {
'en':[
['Graphic design','A visual identity people recognize.','Logo & corporate design|Branding & visual identity|Flyers & posters|Social media graphics|Advertising materials|Print design|Promotional materials'],
['Web design','A professional home for your business online.','Website design|Landing pages|Business websites|Portfolio websites|Online presentation|Website content & visuals|Social media integration'],
['Product design','Turn a concept into something people remember.','Product concepts|Packaging design|Merchandise|Promotional products|Labels & print products|Product presentation|Custom designs'],
['Marketing & social media','Reach the people who matter to your brand.','Social media marketing|Content creation|Campaigns|Promotion|Brand positioning|Digital marketing|Influencer & talent collaborations'],
['Photo & video','Make your story seen, heard, and felt.','Professional photography|Videography|Event coverage|Promotional videos|Social media content|Artist & talent shoots|Product photography'],
['Management & talent','Connect ambition with the right opportunities.','Personal management|Artist management|Sports management|Talent development|Booking|Career positioning|International opportunities'],
['Events & production','Bring your idea into the spotlight.','Event planning|Event coordination|Event promotion|Artist & talent booking|Production support|Launch events|International events'],
['Print & promotional products','Make your brand tangible, beyond the screen.','Flyers|Posters|Business cards|Brochures|Banners|Merchandise|Promotional products|Custom printing']],
'es':[
['Diseño gráfico','Una identidad visual que las personas reconocen.','Diseño de logotipos e imagen corporativa|Marca e identidad visual|Folletos y carteles|Gráficos para redes sociales|Material publicitario|Diseño para impresión|Material promocional'],
['Diseño web','Una presencia profesional para tu negocio en internet.','Diseño de sitios web|Páginas de destino|Sitios web empresariales|Sitios web de portafolio|Presentación en línea|Contenido e imágenes para sitios web|Integración de redes sociales'],
['Diseño de productos','Transforma una idea en algo memorable.','Conceptos de productos|Diseño de envases|Merchandising|Productos promocionales|Etiquetas y productos impresos|Presentación de productos|Diseños personalizados'],
['Marketing y redes sociales','Conecta con las personas que importan a tu marca.','Marketing en redes sociales|Creación de contenido|Campañas|Promoción|Posicionamiento de marca|Marketing digital|Colaboraciones con influencers y talentos'],
['Fotografía y vídeo','Haz que tu historia se vea, se escuche y se sienta.','Fotografía profesional|Videografía|Cobertura de eventos|Vídeos promocionales|Contenido para redes sociales|Sesiones para artistas y talentos|Fotografía de productos'],
['Representación y talento','Conecta la ambición con las oportunidades adecuadas.','Representación personal|Representación de artistas|Representación deportiva|Desarrollo de talentos|Contrataciones|Posicionamiento profesional|Oportunidades internacionales'],
['Eventos y producción','Lleva tu idea al centro de atención.','Planificación de eventos|Coordinación de eventos|Promoción de eventos|Contratación de artistas y talentos|Apoyo a la producción|Eventos de lanzamiento|Eventos internacionales'],
['Impresión y productos promocionales','Tu marca, más allá de la pantalla.','Folletos|Carteles|Tarjetas de visita|Catálogos|Banderolas|Merchandising|Productos promocionales|Impresión personalizada']],
'pt':[
['Design gráfico','Uma identidade visual que as pessoas reconhecem.','Logotipo e design corporativo|Marca e identidade visual|Panfletos e cartazes|Artes para redes sociais|Materiais publicitários|Design para impressão|Materiais promocionais'],
['Web design','Uma presença profissional para seu negócio na internet.','Design de sites|Landing pages|Sites empresariais|Sites de portfólio|Apresentação online|Conteúdo e imagens para sites|Integração com redes sociais'],
['Design de produtos','Transforme uma ideia em algo memorável.','Conceitos de produtos|Design de embalagens|Merchandising|Produtos promocionais|Rótulos e produtos impressos|Apresentação de produtos|Designs personalizados'],
['Marketing e redes sociais','Alcance as pessoas que importam para sua marca.','Marketing nas redes sociais|Criação de conteúdo|Campanhas|Promoção|Posicionamento de marca|Marketing digital|Colaborações com influenciadores e talentos'],
['Foto e vídeo','Faça sua história ser vista, ouvida e sentida.','Fotografia profissional|Videografia|Cobertura de eventos|Vídeos promocionais|Conteúdo para redes sociais|Ensaios de artistas e talentos|Fotografia de produtos'],
['Gestão e talentos','Conecte a ambição às oportunidades certas.','Gestão pessoal|Gestão de artistas|Gestão esportiva|Desenvolvimento de talentos|Agenciamento|Posicionamento de carreira|Oportunidades internacionais'],
['Eventos e produção','Coloque sua ideia em destaque.','Planejamento de eventos|Coordenação de eventos|Promoção de eventos|Contratação de artistas e talentos|Apoio à produção|Eventos de lançamento|Eventos internacionais'],
['Impressão e produtos promocionais','Sua marca, além da tela.','Panfletos|Cartazes|Cartões de visita|Brochuras|Banners|Merchandising|Produtos promocionais|Impressão personalizada']],
'fr':[
['Design graphique','Une identité visuelle que l’on reconnaît.','Logo et design d’entreprise|Marque et identité visuelle|Flyers et affiches|Visuels pour les réseaux sociaux|Supports publicitaires|Design pour l’impression|Supports promotionnels'],
['Design web','Une présence professionnelle pour votre activité en ligne.','Création de sites web|Pages de destination|Sites d’entreprise|Sites portfolio|Présentation en ligne|Contenus et visuels web|Intégration des réseaux sociaux'],
['Design produit','Transformez une idée en quelque chose de mémorable.','Concepts de produits|Design d’emballages|Produits dérivés|Produits promotionnels|Étiquettes et produits imprimés|Présentation de produits|Designs personnalisés'],
['Marketing et réseaux sociaux','Touchez les personnes qui comptent pour votre marque.','Marketing sur les réseaux sociaux|Création de contenu|Campagnes|Promotion|Positionnement de marque|Marketing digital|Collaborations avec influenceurs et talents'],
['Photo et vidéo','Donnez à votre histoire une image, une voix et une émotion.','Photographie professionnelle|Vidéographie|Couverture d’événements|Vidéos promotionnelles|Contenus pour les réseaux sociaux|Séances pour artistes et talents|Photographie de produits'],
['Management et talents','Reliez l’ambition aux bonnes opportunités.','Management personnel|Management d’artistes|Management sportif|Développement de talents|Booking|Positionnement de carrière|Opportunités internationales'],
['Événements et production','Placez votre idée sous les projecteurs.','Planification d’événements|Coordination d’événements|Promotion d’événements|Booking d’artistes et de talents|Soutien à la production|Événements de lancement|Événements internationaux'],
['Impression et produits promotionnels','Votre marque, au-delà de l’écran.','Flyers|Affiches|Cartes de visite|Brochures|Bannières|Produits dérivés|Produits promotionnels|Impression personnalisée']],
'de':[
['Grafikdesign','Eine visuelle Identität mit Wiedererkennungswert.','Logo und Corporate Design|Branding und visuelle Identität|Flyer und Plakate|Social-Media-Grafiken|Werbematerialien|Printdesign|Promotionsmaterialien'],
['Webdesign','Ein professioneller Online-Auftritt für dein Unternehmen.','Websitedesign|Landingpages|Unternehmenswebsites|Portfolio-Websites|Online-Präsentation|Website-Inhalte und Bildwelten|Social-Media-Integration'],
['Produktdesign','Aus einer Idee wird etwas, das in Erinnerung bleibt.','Produktkonzepte|Verpackungsdesign|Merchandise|Werbeartikel|Etiketten und Druckprodukte|Produktpräsentation|Individuelle Designs'],
['Marketing und Social Media','Erreiche die Menschen, die für deine Marke zählen.','Social-Media-Marketing|Content-Erstellung|Kampagnen|Promotion|Markenpositionierung|Digitales Marketing|Kooperationen mit Influencern und Talenten'],
['Foto und Video','Mache deine Geschichte sichtbar, hörbar und spürbar.','Professionelle Fotografie|Videografie|Eventbegleitung|Promotionsvideos|Social-Media-Inhalte|Shootings für Künstler und Talente|Produktfotografie'],
['Management und Talente','Verbinde Ambition mit passenden Chancen.','Persönliches Management|Künstlermanagement|Sportmanagement|Talententwicklung|Booking|Karrierepositionierung|Internationale Möglichkeiten'],
['Events und Produktion','Bringe deine Idee ins Rampenlicht.','Eventplanung|Eventkoordination|Eventpromotion|Künstler- und Talentbooking|Produktionsunterstützung|Launch-Events|Internationale Events'],
['Print und Werbeartikel','Deine Marke, auch jenseits des Bildschirms.','Flyer|Plakate|Visitenkarten|Broschüren|Banner|Merchandise|Werbeartikel|Individueller Druck']],
'it':[
['Design grafico','Un’identità visiva che le persone riconoscono.','Logo e design aziendale|Branding e identità visiva|Volantini e poster|Grafica per i social media|Materiali pubblicitari|Design per la stampa|Materiali promozionali'],
['Web design','Una presenza professionale per la tua attività online.','Design di siti web|Landing page|Siti web aziendali|Siti portfolio|Presentazione online|Contenuti e immagini per siti web|Integrazione dei social media'],
['Design di prodotto','Trasforma un’idea in qualcosa di memorabile.','Concept di prodotto|Design del packaging|Merchandising|Prodotti promozionali|Etichette e prodotti stampati|Presentazione di prodotti|Design personalizzati'],
['Marketing e social media','Raggiungi le persone che contano per il tuo brand.','Social media marketing|Creazione di contenuti|Campagne|Promozione|Posizionamento del brand|Marketing digitale|Collaborazioni con influencer e talenti'],
['Foto e video','Fai vedere, ascoltare e sentire la tua storia.','Fotografia professionale|Videografia|Copertura di eventi|Video promozionali|Contenuti per i social media|Shooting per artisti e talenti|Fotografia di prodotto'],
['Management e talenti','Collega l’ambizione alle opportunità giuste.','Management personale|Management artistico|Management sportivo|Sviluppo dei talenti|Booking|Posizionamento di carriera|Opportunità internazionali'],
['Eventi e produzione','Porta la tua idea sotto i riflettori.','Pianificazione di eventi|Coordinamento di eventi|Promozione di eventi|Booking di artisti e talenti|Supporto alla produzione|Eventi di lancio|Eventi internazionali'],
['Stampa e prodotti promozionali','Il tuo brand, oltre lo schermo.','Volantini|Poster|Biglietti da visita|Brochure|Banner|Merchandising|Prodotti promozionali|Stampa personalizzata']]
}

COPY = {
'en':{
'title':'Creative, marketing, media & talent agency','meta':'Fame Agents brings design, web, marketing, media, talent management and events together. Based in the EU, working worldwide. Start your project.',
'nav':['Services','Approach','About','Contact'],'start':'Start a project','region':'EU based. Worldwide ambition.','hero':['FROM IDEA','TO IMPACT.'],'intro':'We create. We design. We promote. We manage. We connect.','lead':'One partner for brands, people, and projects ready to move forward. Creative thinking. Connected services. International perspective.','explore':'Explore our services','disciplines':'CREATIVE · MARKETING · MANAGEMENT · MEDIA · EVENTS','eyebrow':'01 / WHAT WE DO','services':'Many disciplines.\nOne direction.','serviceintro':'Start with one service or connect several. We build the right combination around your goal.','details':'Explore deliverables','request':'Add to my brief','selected':'Added to brief','abouttag':'03 / WHO WE ARE','abouttitle':'MORE THAN\nAN AGENCY.','abouttext':'Fame Agents brings creative services, marketing, design, media, events, and professional management together to develop people, brands, and projects. From the first idea to the final execution, we connect the skills your project needs.','values':'Forward Ambition. Mastery. Excellence.','oneteam':'One partner. Multiple services. International perspective.','processlabel':'02 / HOW WE WORK','processtitle':'A clear path from\nidea to execution.','steps':[['Discover','We discuss your goal, audience, priorities, and budget.'],['Define','We agree on the scope, deliverables, timing, and quote.'],['Create','We develop the work with review points along the way.'],['Deliver','We prepare the agreed assets, launch, production, or event.']],
'world':'EU roots.\nGlobal perspective.','worldtext':'Building a brand, launching a product, developing a career, or producing an event? Tell us where you want to go. We will discuss how to get there together.','socialtitle':'See our world.','socialtext':'Explore our channels for the people, ideas, and activity behind Fame Agents.','faqtitle':'Good questions.\nClear answers.','faqs':[['Can I book just one service?','Yes. Bring us a specific task, or ask us to connect several services into one project.'],['How much does a project cost?','Every quote is based on scope. We discuss creative work, production, printing, advertising spend, travel, third-party tools, and any applicable taxes before you commit. Nothing is commissioned until the scope and cost are agreed.'],['Do you work internationally?','Yes. We are based in the EU and work with people worldwide. Delivery arrangements, locations, and languages are agreed for each project.'],['Where can I see your work?','Explore our public social channels, or request relevant examples when you contact us. We can discuss work suited to your particular project.']],
'contacttag':'04 / LET’S BUILD SOMETHING','contacttitle':'YOU HAVE\nTHE IDEA.','contactsub':'Let’s bring it to life.','contacttext':'Tell us what you have in mind. Choose the services you need and prepare a project email.','name':'Your name','email':'Your email','company':'Company / project','need':'What do you need?','message':'Your idea','placeholder':'What do you want to create, who is it for, and when do you need it?','budget':'Budget range','budgetoptions':['Let’s discuss','Under €1,000','€1,000–€3,000','€3,000–€10,000','€10,000+'],'timing':'Target date / timing','timingplaceholder':'e.g. Spring 2027, or flexible','prepare':'Preview project email','privacyhint':'This form prepares an email on your device. Nothing is sent until you send it from your email app.','preview':'Your project email','openmail':'Open email app','download':'Download brief','close':'Close','fallback':'If your email app does not open, download the brief and email it to info@fameagents.de.','direct':'Prefer to talk directly?','us':'United States','italy':'Italy / EU','germany':'Germany / EU','footer':'Create. Design. Promote. Manage. Connect.','legal':'Legal & privacy','skip':'Skip to content','menu':'Menu','language':'Language','art':'Original brand artwork','emailSubject':'New project enquiry','briefTitle':'Fame Agents project brief','status':'Your selected service has been added to the project brief.','noscript':'To send a project enquiry, email info@fameagents.de directly.'},
'es':{
'title':'Agencia creativa, marketing, medios y talento','meta':'Fame Agents reúne diseño, web, marketing, medios, representación de talentos y eventos. Con base en la UE y alcance mundial. Empieza tu proyecto.',
'nav':['Servicios','Proceso','Nosotros','Contacto'],'start':'Empieza un proyecto','region':'Base en la UE. Ambición global.','hero':['DE LA IDEA','AL IMPACTO.'],'intro':'Creamos. Diseñamos. Promocionamos. Gestionamos. Conectamos.','lead':'Un aliado para marcas, personas y proyectos que quieren avanzar. Ideas creativas. Servicios conectados. Perspectiva internacional.','explore':'Explora nuestros servicios','disciplines':'CREATIVIDAD · MARKETING · GESTIÓN · MEDIOS · EVENTOS','eyebrow':'01 / QUÉ HACEMOS','services':'Muchas disciplinas.\nUna dirección.','serviceintro':'Empieza con un servicio o combina varios. Creamos la combinación adecuada para tu objetivo.','details':'Ver servicios incluidos','request':'Añadir a mi propuesta','selected':'Añadido a tu propuesta','abouttag':'03 / QUIÉNES SOMOS','abouttitle':'MÁS QUE\nUNA AGENCIA.','abouttext':'Fame Agents reúne servicios creativos, marketing, diseño, medios, eventos y representación profesional para desarrollar personas, marcas y proyectos. Desde la primera idea hasta la ejecución final, conectamos las capacidades que tu proyecto necesita.','values':'Ambición para avanzar. Dominio. Excelencia.','oneteam':'Un aliado. Múltiples servicios. Perspectiva internacional.','processlabel':'02 / CÓMO TRABAJAMOS','processtitle':'Un camino claro de\nla idea a la ejecución.','steps':[['Descubrir','Hablamos de tu objetivo, público, prioridades y presupuesto.'],['Definir','Acordamos el alcance, los entregables, el calendario y el presupuesto.'],['Crear','Desarrollamos el trabajo con revisiones durante el proceso.'],['Entregar','Preparamos los materiales, el lanzamiento, la producción o el evento acordados.']],
'world':'Raíces europeas.\nPerspectiva global.','worldtext':'¿Quieres construir una marca, lanzar un producto, desarrollar una carrera o producir un evento? Cuéntanos adónde quieres llegar. Hablaremos de cómo hacerlo juntos.','socialtitle':'Descubre nuestro mundo.','socialtext':'Explora nuestros canales para conocer las personas, las ideas y la actividad de Fame Agents.','faqtitle':'Buenas preguntas.\nRespuestas claras.','faqs':[['¿Puedo contratar un solo servicio?','Sí. Puedes encargarnos una tarea concreta o pedirnos que conectemos varios servicios en un proyecto.'],['¿Cuánto cuesta un proyecto?','Cada presupuesto depende del alcance. Hablamos del trabajo creativo, producción, impresión, inversión publicitaria, viajes, herramientas externas e impuestos aplicables antes de que te comprometas. No encargamos nada hasta acordar el alcance y el coste.'],['¿Trabajan internacionalmente?','Sí. Tenemos base en la UE y trabajamos con personas de todo el mundo. Acordamos la entrega, las ubicaciones y los idiomas para cada proyecto.'],['¿Dónde puedo ver su trabajo?','Explora nuestros canales públicos o pide ejemplos relevantes cuando nos contactes. Podemos hablar del trabajo más adecuado para tu proyecto.']],
'contacttag':'04 / CREEMOS ALGO JUNTOS','contacttitle':'TÚ TIENES\nLA IDEA.','contactsub':'Hagámosla realidad.','contacttext':'Cuéntanos qué tienes en mente. Elige los servicios y prepara un correo con tu proyecto.','name':'Tu nombre','email':'Tu correo electrónico','company':'Empresa / proyecto','need':'¿Qué necesitas?','message':'Tu idea','placeholder':'¿Qué quieres crear, para quién y para cuándo?','budget':'Rango de presupuesto','budgetoptions':['Hablemos','Menos de 1.000 €','1.000–3.000 €','3.000–10.000 €','Más de 10.000 €'],'timing':'Fecha / plazo deseado','timingplaceholder':'Por ejemplo, primavera de 2027 o flexible','prepare':'Ver correo del proyecto','privacyhint':'Este formulario prepara un correo en tu dispositivo. No se envía nada hasta que lo envíes desde tu aplicación de correo.','preview':'El correo de tu proyecto','openmail':'Abrir aplicación de correo','download':'Descargar resumen','close':'Cerrar','fallback':'Si la aplicación no se abre, descarga el resumen y envíalo a info@fameagents.de.','direct':'¿Prefieres hablar directamente?','us':'Estados Unidos','italy':'Italia / UE','germany':'Alemania / UE','footer':'Crear. Diseñar. Promocionar. Gestionar. Conectar.','legal':'Información legal y privacidad','skip':'Ir al contenido','menu':'Menú','language':'Idioma','art':'Imagen original de marca','emailSubject':'Consulta sobre un nuevo proyecto','briefTitle':'Resumen del proyecto para Fame Agents','status':'El servicio seleccionado se añadió al resumen del proyecto.','noscript':'Para consultar sobre un proyecto, escribe directamente a info@fameagents.de.'},
'pt':{
'title':'Agência criativa, marketing, mídia e talentos','meta':'A Fame Agents reúne design, web, marketing, mídia, gestão de talentos e eventos. Base na UE, atuação mundial. Comece seu projeto.',
'nav':['Serviços','Processo','Sobre','Contato'],'start':'Comece um projeto','region':'Base na UE. Ambição global.','hero':['DA IDEIA','AO IMPACTO.'],'intro':'Criamos. Projetamos. Promovemos. Gerenciamos. Conectamos.','lead':'Um parceiro para marcas, pessoas e projetos prontos para avançar. Ideias criativas. Serviços conectados. Perspectiva internacional.','explore':'Explore nossos serviços','disciplines':'CRIATIVIDADE · MARKETING · GESTÃO · MÍDIA · EVENTOS','eyebrow':'01 / O QUE FAZEMOS','services':'Muitas disciplinas.\nUma direção.','serviceintro':'Comece com um serviço ou combine vários. Criamos a combinação certa para seu objetivo.','details':'Ver entregas incluídas','request':'Adicionar ao meu resumo','selected':'Adicionado ao resumo','abouttag':'03 / QUEM SOMOS','abouttitle':'MAIS QUE\nUMA AGÊNCIA.','abouttext':'A Fame Agents reúne serviços criativos, marketing, design, mídia, eventos e gestão profissional para desenvolver pessoas, marcas e projetos. Da primeira ideia à execução final, conectamos as competências que seu projeto precisa.','values':'Ambição para avançar. Domínio. Excelência.','oneteam':'Um parceiro. Vários serviços. Perspectiva internacional.','processlabel':'02 / COMO TRABALHAMOS','processtitle':'Um caminho claro da\nideia à execução.','steps':[['Descobrir','Conversamos sobre seu objetivo, público, prioridades e orçamento.'],['Definir','Combinamos o escopo, as entregas, o prazo e o orçamento.'],['Criar','Desenvolvemos o trabalho com etapas de revisão.'],['Entregar','Preparamos os materiais, o lançamento, a produção ou o evento combinados.']],
'world':'Raízes europeias.\nPerspectiva global.','worldtext':'Quer construir uma marca, lançar um produto, desenvolver uma carreira ou produzir um evento? Conte aonde você quer chegar. Vamos conversar sobre como fazer isso juntos.','socialtitle':'Conheça nosso mundo.','socialtext':'Explore nossos canais para conhecer as pessoas, ideias e atividades da Fame Agents.','faqtitle':'Boas perguntas.\nRespostas claras.','faqs':[['Posso contratar apenas um serviço?','Sim. Traga uma tarefa específica ou peça para conectarmos vários serviços em um projeto.'],['Quanto custa um projeto?','Cada orçamento depende do escopo. Conversamos sobre criação, produção, impressão, investimento em publicidade, viagens, ferramentas externas e impostos aplicáveis antes de você se comprometer. Nada é contratado antes de combinar o escopo e o custo.'],['Vocês trabalham internacionalmente?','Sim. Temos base na UE e trabalhamos com pessoas no mundo todo. Entregas, locais e idiomas são combinados para cada projeto.'],['Onde posso ver o trabalho de vocês?','Explore nossos canais públicos ou peça exemplos relevantes ao entrar em contato. Podemos conversar sobre trabalhos adequados ao seu projeto.']],
'contacttag':'04 / VAMOS CRIAR ALGO','contacttitle':'VOCÊ TEM\nA IDEIA.','contactsub':'Vamos torná-la realidade.','contacttext':'Conte o que você tem em mente. Escolha os serviços e prepare um e-mail sobre seu projeto.','name':'Seu nome','email':'Seu e-mail','company':'Empresa / projeto','need':'Do que você precisa?','message':'Sua ideia','placeholder':'O que você quer criar, para quem e para quando?','budget':'Faixa de orçamento','budgetoptions':['Vamos conversar','Menos de €1.000','€1.000–€3.000','€3.000–€10.000','Mais de €10.000'],'timing':'Data / prazo desejado','timingplaceholder':'Por exemplo, início de 2027 ou flexível','prepare':'Visualizar e-mail do projeto','privacyhint':'Este formulário prepara um e-mail no seu dispositivo. Nada é enviado até você enviar pela sua aplicação de e-mail.','preview':'O e-mail do seu projeto','openmail':'Abrir aplicação de e-mail','download':'Baixar resumo','close':'Fechar','fallback':'Se a aplicação não abrir, baixe o resumo e envie para info@fameagents.de.','direct':'Prefere conversar diretamente?','us':'Estados Unidos','italy':'Itália / UE','germany':'Alemanha / UE','footer':'Criar. Projetar. Promover. Gerenciar. Conectar.','legal':'Informações legais e privacidade','skip':'Ir para o conteúdo','menu':'Menu','language':'Idioma','art':'Arte original da marca','emailSubject':'Consulta sobre um novo projeto','briefTitle':'Resumo de projeto para a Fame Agents','status':'O serviço selecionado foi adicionado ao resumo do projeto.','noscript':'Para consultar sobre um projeto, escreva diretamente para info@fameagents.de.'},
'fr':{
'title':'Agence créative, marketing, médias et talents','meta':'Fame Agents réunit design, web, marketing, médias, management de talents et événements. Basée dans l’UE, active dans le monde entier.',
'nav':['Services','Méthode','À propos','Contact'],'start':'Lancer un projet','region':'Basés dans l’UE. Ambition mondiale.','hero':['DE L’IDÉE','À L’IMPACT.'],'intro':'Nous créons. Nous concevons. Nous promouvons. Nous gérons. Nous connectons.','lead':'Un partenaire pour les marques, les personnes et les projets qui veulent avancer. Créativité. Services connectés. Perspective internationale.','explore':'Découvrez nos services','disciplines':'CRÉATION · MARKETING · MANAGEMENT · MÉDIAS · ÉVÉNEMENTS','eyebrow':'01 / NOS EXPERTISES','services':'Plusieurs disciplines.\nUne direction.','serviceintro':'Choisissez un service ou combinez-en plusieurs. Nous construisons la bonne combinaison autour de votre objectif.','details':'Voir les prestations','request':'Ajouter à mon brief','selected':'Ajouté au brief','abouttag':'03 / QUI NOUS SOMMES','abouttitle':'PLUS QU’\nUNE AGENCE.','abouttext':'Fame Agents réunit services créatifs, marketing, design, médias, événements et management professionnel pour développer des personnes, des marques et des projets. De la première idée à l’exécution finale, nous connectons les compétences nécessaires à votre projet.','values':'Ambition pour avancer. Maîtrise. Excellence.','oneteam':'Un partenaire. Plusieurs services. Une perspective internationale.','processlabel':'02 / NOTRE MÉTHODE','processtitle':'Un chemin clair de\nl’idée à la réalisation.','steps':[['Découvrir','Nous échangeons sur votre objectif, votre public, vos priorités et votre budget.'],['Définir','Nous convenons du périmètre, des livrables, du calendrier et du devis.'],['Créer','Nous développons le travail avec des étapes de validation.'],['Livrer','Nous préparons les éléments, le lancement, la production ou l’événement convenus.']],
'world':'Racines européennes.\nPerspective mondiale.','worldtext':'Créer une marque, lancer un produit, développer une carrière ou produire un événement ? Dites-nous où vous voulez aller. Nous discuterons du chemin à parcourir ensemble.','socialtitle':'Découvrez notre univers.','socialtext':'Explorez nos réseaux pour découvrir les personnes, les idées et l’activité de Fame Agents.','faqtitle':'Bonnes questions.\nRéponses claires.','faqs':[['Puis-je réserver un seul service ?','Oui. Confiez-nous une mission précise ou demandez-nous de réunir plusieurs services dans un projet.'],['Combien coûte un projet ?','Chaque devis dépend du périmètre. Nous discutons de la création, de la production, de l’impression, des dépenses publicitaires, des déplacements, des outils tiers et des taxes applicables avant tout engagement. Rien n’est commandé avant l’accord sur le périmètre et le coût.'],['Travaillez-vous à l’international ?','Oui. Nous sommes basés dans l’UE et travaillons avec des personnes dans le monde entier. Les modalités de livraison, les lieux et les langues sont convenus pour chaque projet.'],['Où puis-je voir votre travail ?','Explorez nos réseaux publics ou demandez des exemples pertinents en nous contactant. Nous pouvons discuter des réalisations adaptées à votre projet.']],
'contacttag':'04 / CRÉONS QUELQUE CHOSE','contacttitle':'VOUS AVEZ\nL’IDÉE.','contactsub':'Donnons-lui vie.','contacttext':'Parlez-nous de votre idée. Choisissez vos services et préparez un e-mail de présentation.','name':'Votre nom','email':'Votre e-mail','company':'Entreprise / projet','need':'De quoi avez-vous besoin ?','message':'Votre idée','placeholder':'Que voulez-vous créer, pour qui et pour quand ?','budget':'Fourchette budgétaire','budgetoptions':['À discuter','Moins de 1 000 €','1 000–3 000 €','3 000–10 000 €','Plus de 10 000 €'],'timing':'Date / délai souhaité','timingplaceholder':'Par exemple, printemps 2027 ou flexible','prepare':'Prévisualiser l’e-mail du projet','privacyhint':'Ce formulaire prépare un e-mail sur votre appareil. Rien n’est envoyé avant votre envoi depuis votre application de messagerie.','preview':'L’e-mail de votre projet','openmail':'Ouvrir la messagerie','download':'Télécharger le brief','close':'Fermer','fallback':'Si votre messagerie ne s’ouvre pas, téléchargez le brief et envoyez-le à info@fameagents.de.','direct':'Vous préférez nous contacter directement ?','us':'États-Unis','italy':'Italie / UE','germany':'Allemagne / UE','footer':'Créer. Concevoir. Promouvoir. Gérer. Connecter.','legal':'Mentions légales et confidentialité','skip':'Aller au contenu','menu':'Menu','language':'Langue','art':'Création visuelle originale de la marque','emailSubject':'Demande pour un nouveau projet','briefTitle':'Brief de projet pour Fame Agents','status':'Le service sélectionné a été ajouté au brief du projet.','noscript':'Pour une demande de projet, écrivez directement à info@fameagents.de.'},
'de':{
'title':'Agentur für Kreativität, Marketing, Medien und Talente','meta':'Fame Agents vereint Design, Web, Marketing, Medien, Talentmanagement und Events. Mit Sitz in der EU, weltweit aktiv. Starte dein Projekt.',
'nav':['Leistungen','Ablauf','Über uns','Kontakt'],'start':'Projekt starten','region':'In der EU zu Hause. Weltweit ambitioniert.','hero':['VON DER IDEE','ZUR WIRKUNG.'],'intro':'Wir kreieren. Wir gestalten. Wir promoten. Wir managen. Wir verbinden.','lead':'Ein Partner für Marken, Menschen und Projekte, die vorankommen wollen. Kreative Ideen. Verbundene Leistungen. Internationale Perspektive.','explore':'Unsere Leistungen entdecken','disciplines':'KREATIVITÄT · MARKETING · MANAGEMENT · MEDIEN · EVENTS','eyebrow':'01 / UNSERE LEISTUNGEN','services':'Viele Disziplinen.\nEine Richtung.','serviceintro':'Starte mit einer Leistung oder kombiniere mehrere. Wir stellen die passende Kombination für dein Ziel zusammen.','details':'Leistungsumfang ansehen','request':'Zu meinem Briefing hinzufügen','selected':'Zum Briefing hinzugefügt','abouttag':'03 / WER WIR SIND','abouttitle':'MEHR ALS\nEINE AGENTUR.','abouttext':'Fame Agents vereint kreative Leistungen, Marketing, Design, Medien, Events und professionelles Management, um Menschen, Marken und Projekte zu entwickeln. Von der ersten Idee bis zur Umsetzung verbinden wir die Kompetenzen, die dein Projekt braucht.','values':'Ambition nach vorn. Meisterschaft. Exzellenz.','oneteam':'Ein Partner. Viele Leistungen. Internationale Perspektive.','processlabel':'02 / UNSER ABLAUF','processtitle':'Ein klarer Weg von\nder Idee zur Umsetzung.','steps':[['Entdecken','Wir besprechen dein Ziel, deine Zielgruppe, Prioritäten und dein Budget.'],['Definieren','Wir vereinbaren Umfang, Ergebnisse, Zeitplan und Angebot.'],['Kreieren','Wir entwickeln die Arbeit mit gemeinsamen Abstimmungen.'],['Liefern','Wir bereiten die vereinbarten Inhalte, den Launch, die Produktion oder das Event vor.']],
'world':'Europäische Wurzeln.\nGlobale Perspektive.','worldtext':'Eine Marke aufbauen, ein Produkt launchen, eine Karriere entwickeln oder ein Event produzieren? Sag uns, wohin du willst. Gemeinsam besprechen wir den Weg dorthin.','socialtitle':'Entdecke unsere Welt.','socialtext':'Entdecke auf unseren Kanälen die Menschen, Ideen und Aktivitäten hinter Fame Agents.','faqtitle':'Gute Fragen.\nKlare Antworten.','faqs':[['Kann ich eine einzelne Leistung buchen?','Ja. Gib uns eine konkrete Aufgabe oder lass uns mehrere Leistungen zu einem Projekt verbinden.'],['Was kostet ein Projekt?','Jedes Angebot hängt vom Umfang ab. Wir besprechen kreative Arbeit, Produktion, Druck, Werbebudget, Reisen, externe Tools und anfallende Steuern vor deiner Zusage. Nichts wird beauftragt, bevor Umfang und Kosten vereinbart sind.'],['Arbeitet ihr international?','Ja. Wir haben unseren Sitz in der EU und arbeiten mit Menschen weltweit. Lieferung, Standorte und Sprachen werden für jedes Projekt vereinbart.'],['Wo kann ich eure Arbeit sehen?','Entdecke unsere öffentlichen Kanäle oder frage bei deiner Kontaktaufnahme nach passenden Beispielen. Wir können Arbeiten besprechen, die zu deinem Projekt passen.']],
'contacttag':'04 / LASS UNS ETWAS SCHAFFEN','contacttitle':'DU HAST\nDIE IDEE.','contactsub':'Lass sie uns verwirklichen.','contacttext':'Erzähl uns, was du vorhast. Wähle deine Leistungen und bereite eine Projekt-E-Mail vor.','name':'Dein Name','email':'Deine E-Mail','company':'Unternehmen / Projekt','need':'Was brauchst du?','message':'Deine Idee','placeholder':'Was möchtest du schaffen, für wen und bis wann?','budget':'Budgetrahmen','budgetoptions':['Lass uns sprechen','Unter 1.000 €','1.000–3.000 €','3.000–10.000 €','Über 10.000 €'],'timing':'Wunschtermin / Zeitrahmen','timingplaceholder':'Zum Beispiel Frühjahr 2027 oder flexibel','prepare':'Projekt-E-Mail ansehen','privacyhint':'Dieses Formular bereitet eine E-Mail auf deinem Gerät vor. Erst wenn du sie in deinem E-Mail-Programm sendest, wird sie verschickt.','preview':'Deine Projekt-E-Mail','openmail':'E-Mail-Programm öffnen','download':'Briefing herunterladen','close':'Schließen','fallback':'Wenn sich dein E-Mail-Programm nicht öffnet, lade das Briefing herunter und sende es an info@fameagents.de.','direct':'Lieber direkt sprechen?','us':'USA','italy':'Italien / EU','germany':'Deutschland / EU','footer':'Kreieren. Gestalten. Promoten. Managen. Verbinden.','legal':'Impressum und Datenschutz','skip':'Zum Inhalt','menu':'Menü','language':'Sprache','art':'Originales Markenmotiv','emailSubject':'Anfrage für ein neues Projekt','briefTitle':'Projektbriefing für Fame Agents','status':'Die ausgewählte Leistung wurde zum Projektbriefing hinzugefügt.','noscript':'Für eine Projektanfrage schreibe direkt an info@fameagents.de.'},
'it':{
'title':'Agenzia creativa, marketing, media e talenti','meta':'Fame Agents riunisce design, web, marketing, media, management dei talenti ed eventi. Con base nell’UE, attiva in tutto il mondo.',
'nav':['Servizi','Metodo','Chi siamo','Contatti'],'start':'Avvia un progetto','region':'Base nell’UE. Ambizione globale.','hero':['DALL’IDEA','ALL’IMPATTO.'],'intro':'Creiamo. Progettiamo. Promuoviamo. Gestiamo. Connettiamo.','lead':'Un partner per brand, persone e progetti pronti ad avanzare. Idee creative. Servizi connessi. Prospettiva internazionale.','explore':'Scopri i nostri servizi','disciplines':'CREATIVITÀ · MARKETING · MANAGEMENT · MEDIA · EVENTI','eyebrow':'01 / COSA FACCIAMO','services':'Molte discipline.\nUna direzione.','serviceintro':'Inizia con un servizio o combinane diversi. Creiamo la combinazione giusta per il tuo obiettivo.','details':'Scopri le prestazioni','request':'Aggiungi al mio brief','selected':'Aggiunto al brief','abouttag':'03 / CHI SIAMO','abouttitle':'PIÙ DI\nUN’AGENZIA.','abouttext':'Fame Agents riunisce servizi creativi, marketing, design, media, eventi e management professionale per sviluppare persone, brand e progetti. Dalla prima idea all’esecuzione finale, connettiamo le competenze necessarie al tuo progetto.','values':'Ambizione per avanzare. Padronanza. Eccellenza.','oneteam':'Un partner. Molti servizi. Prospettiva internazionale.','processlabel':'02 / COME LAVORIAMO','processtitle':'Un percorso chiaro\ndall’idea alla realizzazione.','steps':[['Scoprire','Parliamo del tuo obiettivo, del pubblico, delle priorità e del budget.'],['Definire','Concordiamo ambito, risultati, tempi e preventivo.'],['Creare','Sviluppiamo il lavoro con momenti di revisione condivisa.'],['Consegnare','Prepariamo i materiali, il lancio, la produzione o l’evento concordati.']],
'world':'Radici europee.\nProspettiva globale.','worldtext':'Vuoi costruire un brand, lanciare un prodotto, sviluppare una carriera o produrre un evento? Dicci dove vuoi arrivare. Parleremo di come farlo insieme.','socialtitle':'Scopri il nostro mondo.','socialtext':'Esplora i nostri canali per conoscere le persone, le idee e le attività di Fame Agents.','faqtitle':'Buone domande.\nRisposte chiare.','faqs':[['Posso prenotare un solo servizio?','Sì. Affidaci un compito specifico o chiedici di collegare più servizi in un progetto.'],['Quanto costa un progetto?','Ogni preventivo dipende dall’ambito. Parliamo di lavoro creativo, produzione, stampa, investimenti pubblicitari, viaggi, strumenti esterni e imposte applicabili prima del tuo impegno. Nulla viene commissionato prima di concordare ambito e costi.'],['Lavorate a livello internazionale?','Sì. Abbiamo base nell’UE e lavoriamo con persone in tutto il mondo. Consegna, località e lingue vengono concordate per ogni progetto.'],['Dove posso vedere i vostri lavori?','Esplora i nostri canali pubblici o richiedi esempi pertinenti quando ci contatti. Possiamo parlare dei lavori adatti al tuo progetto.']],
'contacttag':'04 / CREIAMO QUALCOSA INSIEME','contacttitle':'TU HAI\nL’IDEA.','contactsub':'Diamole vita.','contacttext':'Raccontaci cosa hai in mente. Scegli i servizi e prepara un’e-mail per il tuo progetto.','name':'Il tuo nome','email':'La tua e-mail','company':'Azienda / progetto','need':'Di cosa hai bisogno?','message':'La tua idea','placeholder':'Cosa vuoi creare, per chi e per quando?','budget':'Fascia di budget','budgetoptions':['Parliamone','Meno di 1.000 €','1.000–3.000 €','3.000–10.000 €','Oltre 10.000 €'],'timing':'Data / tempistiche desiderate','timingplaceholder':'Per esempio, primavera 2027 o flessibile','prepare':'Anteprima dell’e-mail del progetto','privacyhint':'Questo modulo prepara un’e-mail sul tuo dispositivo. Nulla viene inviato finché non la invii dalla tua applicazione e-mail.','preview':'L’e-mail del tuo progetto','openmail':'Apri applicazione e-mail','download':'Scarica il brief','close':'Chiudi','fallback':'Se l’applicazione non si apre, scarica il brief e invialo a info@fameagents.de.','direct':'Preferisci parlare direttamente?','us':'Stati Uniti','italy':'Italia / UE','germany':'Germania / UE','footer':'Creare. Progettare. Promuovere. Gestire. Connettere.','legal':'Informazioni legali e privacy','skip':'Vai al contenuto','menu':'Menu','language':'Lingua','art':'Visual originale del brand','emailSubject':'Richiesta per un nuovo progetto','briefTitle':'Brief di progetto per Fame Agents','status':'Il servizio selezionato è stato aggiunto al brief del progetto.','noscript':'Per una richiesta di progetto, scrivi direttamente a info@fameagents.de.'}
}

from focus import apply_focus
apply_focus(COPY, SERVICES)
for language, delivery in {'en':'We prepare the agreed assets, launch your website, or start your content schedule.', 'es':'Preparamos los materiales, lanzamos tu sitio o iniciamos el calendario de contenido.', 'pt':'Preparamos os materiais, lançamos seu site ou iniciamos o calendário de conteúdo.', 'fr':'Nous préparons les éléments, lançons votre site ou démarrons votre calendrier de contenu.', 'de':'Wir bereiten die Inhalte vor, starten deine Website oder beginnen deinen Content-Plan.', 'it':'Prepariamo i materiali, lanciamo il tuo sito o avviamo il calendario dei contenuti.'}.items():
    COPY[language]['steps'][-1][1] = delivery

def text(s): return esc(s).replace('\n','<br>')
def url(lang): return '/' if lang == 'en' else f'/{lang}/'
def icon(i):
    paths = ['M5 19l3-7L18 2l4 4-10 10-7 3zm3-7 4 4M16 4l4 4','M2 5h20v14H2zM2 9h20M7 7h.01M5 22h14M12 19v3','M12 2l10 5v10l-10 5-10-5V7l10-5zm0 10 10-5M12 12v10M2 7l10 5','M3 13V8l15-5v15L3 13zm0 0 3 8h4l-3-7M21 7v7','M3 6h13v13H3zM16 10l6-3v11l-6-3M8 3h3','M12 12a5 5 0 1 0 0-10 5 5 0 0 0 0 10zM3 23v-3a9 9 0 0 1 18 0v3','M3 5h18v16H3zM3 10h18M7 2v6M17 2v6M8 16l3 3 5-5','M6 8V2h12v6M6 17H2V8h20v9h-4M6 14h12v8H6zM18 11h.01']
    return f'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="{paths[[1,4,3][i]]}"/></svg>'

for lang, language_name in LANGS:
    c = COPY[lang]; sv = SERVICES[lang]
    prefix = './' if lang == 'en' else '../'
    asset = prefix + 'assets/'
    langlinks = ''.join('<a href="'+(prefix if k=='en' else prefix+k+'/')+'" lang="'+k+'" hreflang="'+k+'" '+('aria-current="page"' if k==lang else '')+'>'+v+'</a>' for k,v in LANGS)
    alternates = ''.join(f'<link rel="alternate" hreflang="{k}" href="https://fameagents.de{url(k)}">' for k,v in LANGS)
    nav = ''.join(f'<a href="#{anchor}">{esc(label)}</a>' for anchor,label in zip(['services','approach','about','contact'],c['nav']))
    cards = ''.join(f'''<article class="service-card" id="service-{i}"><div class="card-top"><span class="number">0{i+1}</span>{icon(i)}</div><h3>{esc(s[0])}</h3><p>{esc(s[1])}</p><details><summary>{esc(c['details'])}<span aria-hidden="true">+</span></summary><ul>{''.join('<li>'+esc(x)+'</li>' for x in s[2].split('|'))}</ul></details><button class="add-service" data-service="{i}" type="button">{esc(c['request'])}<span aria-hidden="true">↗</span></button></article>''' for i,s in enumerate(sv))
    steps = ''.join(f'<article><span class="step-no">0{i+1}</span><h3>{esc(t)}</h3><p>{esc(d)}</p></article>' for i,(t,d) in enumerate(c['steps']))
    checks = ''.join(f'<label class="check"><input type="checkbox" name="services" value="{esc(s[0])}" id="choice-{i}"><span>{esc(s[0])}</span></label>' for i,s in enumerate(sv))
    socials = ''.join(f'<a href="{esc(h)}" target="_blank" rel="noopener noreferrer">{n}<span aria-hidden="true">↗</span></a>' for n,h in SOCIALS)
    faq = ''.join(f'<details><summary>{esc(q)}<span aria-hidden="true">+</span></summary><p>{esc(a)}</p></details>' for q,a in c['faqs'])
    jsonld = {'@context':'https://schema.org','@type':'Organization','name':'Fame Agents','url':'https://fameagents.de','email':'info@fameagents.de','sameAs':[h for n,h in SOCIALS],'contactPoint':[{'@type':'ContactPoint','telephone':p,'contactType':'customer enquiries','availableLanguage':[n for l,n in LANGS]} for p in ['+1 850 721 2327','+39 149 707 3725','+49 7131 207 9170']]}
    html = f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fame Agents | {esc(c['title'])}</title><meta name="description" content="{esc(c['meta'])}"><meta name="theme-color" content="#151515"><link rel="canonical" href="https://fameagents.de{url(lang)}">{alternates}<link rel="alternate" hreflang="x-default" href="https://fameagents.de/"><meta property="og:type" content="website"><meta property="og:title" content="Fame Agents | {esc(c['title'])}"><meta property="og:description" content="{esc(c['meta'])}"><meta property="og:url" content="https://fameagents.de{url(lang)}"><meta property="og:image" content="https://fameagents.de/assets/social-card.svg"><link rel="icon" href="{asset}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{asset}style.css"><script src="{asset}app.js" defer></script><script type="application/ld+json">{json.dumps(jsonld,ensure_ascii=False)}</script></head>
<body><a class="skip" href="#main">{esc(c['skip'])}</a>
<header class="site-header"><a class="wordmark" href="#" aria-label="Fame Agents">FAME<span>AGENTS<span class="brand-dot">●</span></span></a><button class="menu-button" type="button" aria-controls="navigation" aria-expanded="false">{esc(c['menu'])} <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="{esc(c['menu'])}">{nav}</nav><div class="header-actions"><details class="language-switch"><summary aria-label="{esc(c['language'])}">{lang.upper()} <span aria-hidden="true">⌄</span></summary><div class="language-options">{langlinks}</div></details><a class="button small" href="#contact">{esc(c['start'])} <span aria-hidden="true">↗</span></a></div></header>
<main id="main"><section class="hero"><div class="hero-art" role="img" aria-label="{esc(c['art'])}"></div><div class="hero-content"><p class="eyebrow"><span class="live-dot"></span>{esc(c['region'])}</p><h1>{esc(c['hero'][0])}<br><span>{esc(c['hero'][1])}</span></h1><p class="hero-intro">{esc(c['intro'])}</p><p class="hero-lead">{esc(c['lead'])}</p><div class="hero-buttons"><a class="button" href="#contact">{esc(c['start'])}<span aria-hidden="true">↗</span></a><a class="text-link" href="#services">{esc(c['explore'])}<span aria-hidden="true">↓</span></a></div></div><div class="hero-bottom"><span>FAME AGENTS</span><span>EU ↔ WORLD</span></div></section>
<div class="discipline-bar">{esc(c['disciplines'])}</div>
<section class="section light" id="services"><div class="section-heading"><div><p class="eyebrow">{esc(c['eyebrow'])}</p><h2>{text(c['services'])}</h2></div><p>{esc(c['serviceintro'])}</p></div><div class="service-grid">{cards}</div></section>
<section class="section process" id="approach"><p class="eyebrow">{esc(c['processlabel'])}</p><h2>{text(c['processtitle'])}</h2><div class="process-grid">{steps}</div></section>
<section class="section about" id="about"><div class="about-art" aria-hidden="true"><span>F</span><span>A</span><span>M</span><span>E</span><div class="orbit"></div></div><div class="about-copy"><p class="eyebrow">{esc(c['abouttag'])}</p><h2>{text(c['abouttitle'])}</h2><p>{esc(c['abouttext'])}</p><p class="values">{esc(c['values'])}</p><p class="one-team">{esc(c['oneteam'])}</p></div></section>
<section class="section world"><div><p class="eyebrow">FAME / WORLDWIDE</p><h2>{text(c['world'])}</h2><p>{esc(c['worldtext'])}</p></div><div class="world-art" aria-hidden="true"><svg viewBox="0 0 500 360"><defs><radialGradient id="g"><stop stop-color="#fd7545"/><stop offset="1" stop-color="#cf4826"/></radialGradient></defs><circle cx="250" cy="180" r="136" fill="url(#g)"/><g fill="none" stroke="#151515" stroke-width="1.5" opacity=".5"><ellipse cx="250" cy="180" rx="70" ry="136"/><ellipse cx="250" cy="180" rx="115" ry="136"/><ellipse cx="250" cy="180" rx="136" ry="54"/><ellipse cx="250" cy="180" rx="136" ry="106"/><path d="M114 180h272M250 44v272"/></g><ellipse cx="250" cy="180" rx="220" ry="73" transform="rotate(-24 250 180)" fill="none" stroke="#f8eee3" stroke-width="2"/><circle cx="438" cy="95" r="7" fill="#f8eee3"/></svg><div class="world-caption">EUROPE → WORLD</div></div></section>
<section class="section social light"><div><p class="eyebrow">FAME / SOCIAL</p><h2>{esc(c['socialtitle'])}</h2><p>{esc(c['socialtext'])}</p></div><div class="social-links">{socials}</div></section>
<section class="section faq light"><h2>{text(c['faqtitle'])}</h2><div>{faq}</div></section>
<section class="section contact" id="contact"><div class="contact-copy"><p class="eyebrow">{esc(c['contacttag'])}</p><h2>{text(c['contacttitle'])}</h2><h3>{esc(c['contactsub'])}</h3><p>{esc(c['contacttext'])}</p><a class="email-link" href="mailto:info@fameagents.de">info@fameagents.de ↗</a><p class="direct">{esc(c['direct'])}</p><div class="phone"><span>{esc(c['us'])}</span><a href="tel:+18507212327">+1 850 721 2327</a></div><div class="phone"><span>{esc(c['italy'])}</span><a href="tel:+391497073725">+39 149 707 3725</a></div><div class="phone"><span>{esc(c['germany'])}</span><a href="tel:+4971312079170">+49 7131 207 9170</a></div></div>
<form id="project-form" action="mailto:info@fameagents.de" method="get"><div class="form-row"><label>{esc(c['name'])}<input name="name" autocomplete="name" required maxlength="120"></label><label>{esc(c['email'])}<input type="email" name="email" autocomplete="email" required maxlength="180"></label></div><label>{esc(c['company'])}<input name="company" autocomplete="organization" maxlength="180"></label><fieldset><legend>{esc(c['need'])}</legend><div class="checkbox-grid">{checks}</div></fieldset><label>{esc(c['message'])}<textarea name="message" required rows="4" maxlength="2500" placeholder="{esc(c['placeholder'])}"></textarea></label><div class="form-row"><label>{esc(c['budget'])}<select name="budget">{''.join('<option>'+esc(o)+'</option>' for o in c['budgetoptions'])}</select></label><label>{esc(c['timing'])}<input name="timing" maxlength="120" placeholder="{esc(c['timingplaceholder'])}"></label></div><button class="button submit" type="submit">{esc(c['prepare'])}<span aria-hidden="true">↗</span></button><p class="privacy-hint">{esc(c['privacyhint'])}</p><noscript><p>{esc(c['noscript'])}</p></noscript></form></section>
</main><footer><a class="wordmark" href="#">FAME<span>AGENTS<span class="brand-dot">●</span></span></a><p>{esc(c['footer'])}</p><div><a href="{prefix}legal.html">{esc(c['legal'])}</a><span>© 2026 Fame Agents</span></div></footer>
<dialog id="brief-dialog" aria-labelledby="brief-title"><div class="dialog-heading"><h2 id="brief-title">{esc(c['preview'])}</h2><button type="button" id="close-dialog" aria-label="{esc(c['close'])}">×</button></div><pre id="brief-preview"></pre><div class="dialog-actions"><a id="email-brief" class="button" href="mailto:info@fameagents.de">{esc(c['openmail'])} ↗</a><button type="button" id="download-brief" class="secondary">{esc(c['download'])}</button></div><p>{esc(c['fallback'])}</p></dialog><div id="status" class="sr-only" role="status"></div>
<script type="application/json" id="page-copy">{json.dumps({k:c[k] for k in ['name','email','company','need','message','budget','timing','emailSubject','briefTitle','selected','request','status']},ensure_ascii=False)}</script>
</body></html>'''
    dest = PUBLIC if lang == 'en' else PUBLIC/lang
    dest.mkdir(parents=True,exist_ok=True)
    html = html.replace('assets/social-card.svg','assets/social-card.png')
    html = html.replace('<details><summary>', '<details open><summary>', 3)
    wa = f'<a class="button whatsapp-link" href="https://wa.me/391497073725" target="_blank" rel="noopener noreferrer">{esc(c["whatsapp"])} <span aria-hidden="true">↗</span></a>'
    html = html.replace('<p class="direct">', wa+'<p class="direct">')
    html = html.replace('<button type="button" id="download-brief"', f'<a id="whatsapp-brief" class="secondary" href="https://wa.me/391497073725" target="_blank" rel="noopener noreferrer">{esc(c["share"])}</a><button type="button" id="download-brief"')
    html = html.replace('<div id="status"', f'<a class="whatsapp-float" href="https://wa.me/391497073725" target="_blank" rel="noopener noreferrer" aria-label="{esc(c["whatsapp"])}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11a8 8 0 0 1-8 8H7l-5 3 2-6a8 8 0 1 1 16-5Z"/><path d="M8 7c0 4 2 6 6 7l2-2-3-2-1 1-2-2 1-1-2-2-1 1Z"/></svg><span>WhatsApp</span></a><div id="status"')
    (dest/'index.html').write_text(html)

(PUBLIC/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>https://fameagents.de{url(k)}</loc></url>' for k,v in LANGS)+'</urlset>')
(PUBLIC/'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /legal.html\nSitemap: https://fameagents.de/sitemap.xml\n')
print('Built six language pages, sitemap and robots.txt')
