"""Approved three-service direction. Public prices are intentionally omitted."""
CONTENT = {
'en': {
'title':'Websites, video editing & social media management',
'meta':'Fame Agents builds business websites, edits short videos and manages social media content. EU based, working worldwide. Request a tailored quote.',
'hero':['WEBSITES.','CONTENT.'], 'intro':'Your business, clearly presented. Your content, consistently delivered.',
'lead':'Website design, short video editing, and social media management for businesses that want a professional online presence. One partner, from the first brief to ongoing support.',
'start':'Request a quote', 'disciplines':'WEBSITE DESIGN · VIDEO EDITING · SOCIAL MEDIA',
'services':'Three services.\nOne partner.', 'serviceintro':'Build your website. Edit your videos. Keep your social channels active. Choose a single project or ongoing monthly support.',
'abouttext':'Fame Agents helps businesses present their services clearly online. We connect website design, video editing, and social media content in one coordinated service. Our wider creative services are available on request.',
'worldtext':'We are based in the EU and work with businesses worldwide. Your audience, preferred language, project scope, and delivery arrangements guide the work.',
'contacttext':'Tell us about your business and what you need. Prepare a project brief, or talk to us directly on WhatsApp. We will discuss the scope and provide a tailored quote.',
'footer':'Websites. Video. Social media.', 'budgetoptions':['Let’s discuss','I have a budget in mind','I need advice on the scope'],
'whatsapp':'Chat on WhatsApp', 'share':'Open WhatsApp with my brief',
'faqs':[['Can I book just one service?','Yes. Book a website project, a video editing package, or social media support. We can also connect them into one coordinated plan.'],['How do I get a quote?','Send your project brief or contact us on WhatsApp. We agree on deliverables, revisions, timing, and costs before work starts. Advertising spend, paid tools, and other third-party costs are identified separately.'],['Do you create the footage?','Our video editing service uses footage you supply. Filming, photography, and complex animation can be discussed and quoted separately.'],['What does social media management include?','Content planning, graphics, captions, scheduling, posting, and a monthly report, according to your agreed package. Daily inbox replies, comment moderation, and paid advertising are separate services.'],['Do you work internationally?','Yes. We work with businesses worldwide. Website languages, content languages, and delivery arrangements are agreed for each project.'],['Where can I see your work?','Explore our public social channels or ask us for relevant examples. We will discuss work suited to your business and project.']],
'servicesData':[
['Website design & redesign','Explain your services. Show your work. Make enquiries easier.','Business websites and landing pages|Website redesign|Mobile and desktop layouts|Service pages and project galleries|Quote enquiry setup and contact links|Basic page titles and search metadata|Website content editing|Optional website care and updates'],
['Short video editing','Make more from the footage you already have.','Reels, TikToks and YouTube Shorts|Promotional video editing|Vertical videos up to 60 seconds|Captions and on-screen text|Basic audio cleanup|Music with appropriate usage rights|Agreed revision rounds|Individual videos or monthly packages'],
['Social media management','Consistent content, with a clear plan.','Monthly content planning|Graphics and captions|Short videos in selected packages|Scheduling and posting|Content adapted for agreed platforms|Monthly performance report|Content approval before publishing|Optional inbox and comment management']]
},
'es': {
'title':'Diseño web, edición de vídeo y gestión de redes sociales','meta':'Fame Agents crea sitios web, edita vídeos cortos y gestiona contenido para redes sociales. Base en la UE, alcance mundial. Solicita un presupuesto.',
'hero':['SITIOS WEB.','CONTENIDO.'],'intro':'Tu negocio, presentado con claridad. Tu contenido, publicado con constancia.',
'lead':'Diseño web, edición de vídeos cortos y gestión de redes sociales para empresas que quieren una presencia profesional en internet. Un aliado, desde la propuesta inicial hasta el apoyo continuo.',
'start':'Solicita un presupuesto','disciplines':'DISEÑO WEB · EDICIÓN DE VÍDEO · REDES SOCIALES',
'services':'Tres servicios.\nUn aliado.','serviceintro':'Crea tu sitio web. Edita tus vídeos. Mantén tus redes activas. Elige un proyecto o un servicio mensual.',
'abouttext':'Fame Agents ayuda a las empresas a presentar sus servicios con claridad en internet. Conectamos diseño web, edición de vídeo y contenido para redes sociales en un servicio coordinado. Ofrecemos otros servicios creativos bajo solicitud.',
'worldtext':'Tenemos base en la UE y trabajamos con empresas de todo el mundo. Tu público, idioma, alcance y necesidades de entrega orientan el proyecto.',
'contacttext':'Cuéntanos sobre tu negocio y lo que necesitas. Prepara un resumen del proyecto o habla con nosotros por WhatsApp. Acordaremos el alcance y prepararemos un presupuesto personalizado.',
'footer':'Sitios web. Vídeo. Redes sociales.','budgetoptions':['Hablemos','Tengo un presupuesto definido','Necesito asesoramiento sobre el alcance'],
'whatsapp':'Habla por WhatsApp','share':'Abrir WhatsApp con mi propuesta',
'faqs':[['¿Puedo contratar un solo servicio?','Sí. Puedes contratar un sitio web, un paquete de edición de vídeo o gestión de redes sociales. También podemos coordinarlos en un plan.'],['¿Cómo solicito un presupuesto?','Envía tu propuesta o contáctanos por WhatsApp. Acordamos entregables, revisiones, plazos y costes antes de comenzar. La inversión publicitaria, herramientas de pago y otros gastos externos se detallan por separado.'],['¿Graban el material?','Nuestro servicio de edición utiliza material que tú proporcionas. La grabación, fotografía y animación compleja se pueden presupuestar por separado.'],['¿Qué incluye la gestión de redes?','Planificación, gráficos, textos, programación, publicación e informe mensual según tu paquete. Respuestas diarias, moderación de comentarios y publicidad de pago son servicios adicionales.'],['¿Trabajan internacionalmente?','Sí. Trabajamos con empresas de todo el mundo. Acordamos los idiomas del sitio y del contenido y las condiciones de entrega para cada proyecto.'],['¿Dónde puedo ver su trabajo?','Explora nuestros canales públicos o pide ejemplos relevantes. Hablaremos del trabajo adecuado para tu negocio.']],
'servicesData':[
['Diseño y rediseño web','Explica tus servicios. Muestra tu trabajo. Facilita las consultas.','Sitios empresariales y páginas de destino|Rediseño de sitios web|Diseño para móviles y ordenadores|Páginas de servicios y galerías|Consultas de presupuesto y enlaces de contacto|Títulos y metadatos básicos para buscadores|Edición de contenido web|Mantenimiento y actualizaciones opcionales'],
['Edición de vídeos cortos','Aprovecha mejor el material que ya tienes.','Reels, TikToks y YouTube Shorts|Edición de vídeos promocionales|Vídeos verticales de hasta 60 segundos|Subtítulos y texto en pantalla|Limpieza básica del audio|Música con derechos de uso adecuados|Rondas de revisión acordadas|Vídeos individuales o paquetes mensuales'],
['Gestión de redes sociales','Contenido constante, con un plan claro.','Planificación mensual de contenido|Gráficos y textos|Vídeos cortos en paquetes seleccionados|Programación y publicación|Adaptación a las plataformas acordadas|Informe mensual de rendimiento|Aprobación antes de publicar|Gestión opcional de mensajes y comentarios']]
},
'pt': {
'title':'Web design, edição de vídeo e gestão de redes sociais','meta':'A Fame Agents cria sites, edita vídeos curtos e gerencia conteúdo nas redes sociais. Base na UE, atuação mundial. Peça um orçamento personalizado.',
'hero':['SITES.','CONTEÚDO.'],'intro':'Seu negócio, apresentado com clareza. Seu conteúdo, publicado com consistência.',
'lead':'Web design, edição de vídeos curtos e gestão de redes sociais para empresas que querem uma presença profissional online. Um parceiro, do primeiro briefing ao suporte contínuo.',
'start':'Peça um orçamento','disciplines':'WEB DESIGN · EDIÇÃO DE VÍDEO · REDES SOCIAIS',
'services':'Três serviços.\nUm parceiro.','serviceintro':'Crie seu site. Edite seus vídeos. Mantenha suas redes ativas. Escolha um projeto ou suporte mensal.',
'abouttext':'A Fame Agents ajuda empresas a apresentar seus serviços com clareza online. Conectamos web design, edição de vídeo e conteúdo para redes sociais em um serviço coordenado. Outros serviços criativos estão disponíveis sob consulta.',
'worldtext':'Temos base na UE e trabalhamos com empresas do mundo todo. Seu público, idioma, escopo e necessidades de entrega orientam o projeto.',
'contacttext':'Conte sobre seu negócio e o que você precisa. Prepare um resumo do projeto ou fale com a gente pelo WhatsApp. Vamos definir o escopo e preparar um orçamento personalizado.',
'footer':'Sites. Vídeo. Redes sociais.','budgetoptions':['Vamos conversar','Tenho um orçamento definido','Preciso de orientação sobre o escopo'],
'whatsapp':'Converse pelo WhatsApp','share':'Abrir WhatsApp com meu resumo',
'faqs':[['Posso contratar apenas um serviço?','Sim. Você pode contratar um site, um pacote de edição de vídeo ou gestão de redes sociais. Também podemos conectar os serviços em um plano.'],['Como peço um orçamento?','Envie seu resumo ou fale pelo WhatsApp. Combinamos entregas, revisões, prazos e custos antes de começar. Publicidade, ferramentas pagas e outros gastos externos são apresentados separadamente.'],['Vocês gravam o material?','A edição usa vídeos que você fornece. Filmagem, fotografia e animação complexa podem ser orçadas separadamente.'],['O que inclui a gestão de redes sociais?','Planejamento, artes, legendas, agendamento, publicação e relatório mensal conforme o pacote. Respostas diárias, moderação de comentários e anúncios pagos são serviços adicionais.'],['Vocês trabalham internacionalmente?','Sim. Trabalhamos com empresas no mundo todo. Idiomas do site e dos conteúdos e condições de entrega são combinados por projeto.'],['Onde posso ver os trabalhos?','Explore nossos canais públicos ou peça exemplos relevantes. Podemos conversar sobre trabalhos adequados ao seu negócio.']],
'servicesData':[
['Design e reformulação de sites','Explique seus serviços. Mostre seu trabalho. Facilite o contato.','Sites empresariais e landing pages|Reformulação de sites|Layouts para celular e computador|Páginas de serviços e galerias|Solicitação de orçamento e links de contato|Títulos e metadados básicos para busca|Edição de conteúdo do site|Manutenção e atualizações opcionais'],
['Edição de vídeos curtos','Aproveite melhor os vídeos que você já tem.','Reels, TikToks e YouTube Shorts|Edição de vídeos promocionais|Vídeos verticais de até 60 segundos|Legendas e textos na tela|Limpeza básica de áudio|Música com direitos de uso adequados|Rodadas de revisão combinadas|Vídeos avulsos ou pacotes mensais'],
['Gestão de redes sociais','Conteúdo consistente, com um plano claro.','Planejamento mensal de conteúdo|Artes e legendas|Vídeos curtos em pacotes selecionados|Agendamento e publicação|Adaptação às plataformas combinadas|Relatório mensal de desempenho|Aprovação antes de publicar|Gestão opcional de mensagens e comentários']]
},
'fr': {
'title':'Sites web, montage vidéo et gestion des réseaux sociaux','meta':'Fame Agents crée des sites web, monte des vidéos courtes et gère les réseaux sociaux. Basée dans l’UE, active dans le monde entier. Demandez un devis.',
'hero':['SITES WEB.','CONTENUS.'],'intro':'Votre activité, présentée clairement. Votre contenu, publié régulièrement.',
'lead':'Création de sites web, montage de vidéos courtes et gestion des réseaux sociaux pour les entreprises qui veulent une présence professionnelle en ligne. Un partenaire, du premier brief au suivi.',
'start':'Demander un devis','disciplines':'SITES WEB · MONTAGE VIDÉO · RÉSEAUX SOCIAUX',
'services':'Trois services.\nUn partenaire.','serviceintro':'Créez votre site. Montez vos vidéos. Animez vos réseaux. Choisissez un projet ponctuel ou un accompagnement mensuel.',
'abouttext':'Fame Agents aide les entreprises à présenter leurs services clairement en ligne. Nous réunissons création web, montage vidéo et contenus pour les réseaux sociaux dans un service coordonné. Nos autres services créatifs sont disponibles sur demande.',
'worldtext':'Nous sommes basés dans l’UE et travaillons avec des entreprises du monde entier. Votre public, votre langue, le périmètre et les modalités de livraison orientent notre travail.',
'contacttext':'Parlez-nous de votre activité et de vos besoins. Préparez un brief ou contactez-nous sur WhatsApp. Nous définirons le périmètre et établirons un devis personnalisé.',
'footer':'Sites web. Vidéo. Réseaux sociaux.','budgetoptions':['À discuter','J’ai un budget défini','J’ai besoin de conseils sur le périmètre'],
'whatsapp':'Discuter sur WhatsApp','share':'Ouvrir WhatsApp avec mon brief',
'faqs':[['Puis-je réserver un seul service ?','Oui. Choisissez un site web, un forfait de montage vidéo ou la gestion des réseaux sociaux. Nous pouvons aussi réunir ces services dans un plan.'],['Comment obtenir un devis ?','Envoyez votre brief ou contactez-nous sur WhatsApp. Nous convenons des livrables, des révisions, du calendrier et des coûts avant de commencer. Publicité, outils payants et autres frais externes sont détaillés séparément.'],['Réalisez-vous les prises de vue ?','Le montage utilise les vidéos que vous fournissez. Le tournage, la photographie et l’animation complexe peuvent être chiffrés séparément.'],['Que comprend la gestion des réseaux sociaux ?','Planification, visuels, textes, programmation, publication et rapport mensuel selon le forfait. Les réponses quotidiennes, la modération et la publicité payante sont des services supplémentaires.'],['Travaillez-vous à l’international ?','Oui. Nous travaillons avec des entreprises du monde entier. Les langues du site et des contenus et les modalités de livraison sont convenues pour chaque projet.'],['Où voir vos réalisations ?','Explorez nos réseaux publics ou demandez des exemples pertinents. Nous pouvons discuter des réalisations adaptées à votre activité.']],
'servicesData':[
['Création et refonte de sites web','Présentez vos services. Montrez votre travail. Facilitez les demandes.','Sites d’entreprise et pages de destination|Refonte de sites web|Design pour mobile et ordinateur|Pages de services et galeries|Demandes de devis et liens de contact|Titres et métadonnées de base pour les moteurs de recherche|Révision des contenus web|Maintenance et mises à jour en option'],
['Montage de vidéos courtes','Valorisez les vidéos que vous avez déjà.','Reels, TikToks et YouTube Shorts|Montage de vidéos promotionnelles|Vidéos verticales jusqu’à 60 secondes|Sous-titres et textes à l’écran|Nettoyage audio de base|Musique avec les droits d’utilisation adaptés|Cycles de révision convenus|Vidéos à l’unité ou forfaits mensuels'],
['Gestion des réseaux sociaux','Des contenus réguliers, avec un plan clair.','Planification mensuelle|Visuels et textes|Vidéos courtes dans certains forfaits|Programmation et publication|Adaptation aux plateformes convenues|Rapport mensuel de performance|Validation avant publication|Gestion des messages et commentaires en option']]
},
'de': {
'title':'Webdesign, Videoschnitt und Social-Media-Management','meta':'Fame Agents erstellt Websites, schneidet Kurzvideos und betreut Social-Media-Inhalte. Mit Sitz in der EU, weltweit aktiv. Individuelles Angebot anfragen.',
'hero':['WEBSITES.','CONTENT.'],'intro':'Dein Unternehmen, klar präsentiert. Dein Content, regelmäßig veröffentlicht.',
'lead':'Webdesign, Kurzvideoschnitt und Social-Media-Management für Unternehmen mit Anspruch an ihren Online-Auftritt. Ein Partner, vom ersten Briefing bis zur laufenden Betreuung.',
'start':'Angebot anfragen','disciplines':'WEBDESIGN · VIDEOSCHNITT · SOCIAL MEDIA',
'services':'Drei Leistungen.\nEin Partner.','serviceintro':'Website erstellen. Videos schneiden. Social Media aktiv halten. Wähle ein Projekt oder laufende monatliche Unterstützung.',
'abouttext':'Fame Agents hilft Unternehmen, ihre Leistungen online klar zu präsentieren. Wir verbinden Webdesign, Videoschnitt und Social-Media-Inhalte in einem abgestimmten Service. Weitere kreative Leistungen sind auf Anfrage verfügbar.',
'worldtext':'Wir haben unseren Sitz in der EU und arbeiten mit Unternehmen weltweit. Zielgruppe, Sprache, Projektumfang und Lieferbedingungen bestimmen unsere Arbeit.',
'contacttext':'Erzähl uns von deinem Unternehmen und deinem Bedarf. Bereite ein Briefing vor oder sprich direkt mit uns auf WhatsApp. Wir besprechen den Umfang und erstellen ein individuelles Angebot.',
'footer':'Websites. Video. Social Media.','budgetoptions':['Lass uns sprechen','Ich habe einen Budgetrahmen','Ich brauche Beratung zum Umfang'],
'whatsapp':'Auf WhatsApp schreiben','share':'WhatsApp mit meinem Briefing öffnen',
'faqs':[['Kann ich eine einzelne Leistung buchen?','Ja. Buche eine Website, ein Videoschnitt-Paket oder Social-Media-Betreuung. Wir können die Leistungen auch zu einem Plan verbinden.'],['Wie bekomme ich ein Angebot?','Sende dein Briefing oder kontaktiere uns auf WhatsApp. Wir vereinbaren Ergebnisse, Korrekturen, Zeitplan und Kosten vor dem Start. Werbebudget, kostenpflichtige Tools und andere externe Kosten werden getrennt aufgeführt.'],['Dreht ihr die Videos?','Unser Videoschnitt nutzt dein bereitgestelltes Material. Dreharbeiten, Fotografie und komplexe Animationen können separat angeboten werden.'],['Was umfasst Social-Media-Management?','Planung, Grafiken, Texte, Terminierung, Veröffentlichung und monatlicher Bericht gemäß deinem Paket. Tägliche Nachrichten, Kommentarmoderation und bezahlte Werbung sind Zusatzleistungen.'],['Arbeitet ihr international?','Ja. Wir arbeiten mit Unternehmen weltweit. Website- und Content-Sprachen sowie Lieferbedingungen werden je Projekt vereinbart.'],['Wo kann ich eure Arbeit sehen?','Entdecke unsere öffentlichen Kanäle oder frage nach passenden Beispielen. Wir besprechen Arbeiten, die zu deinem Unternehmen passen.']],
'servicesData':[
['Webdesign und Website-Relaunch','Leistungen erklären. Arbeit zeigen. Anfragen erleichtern.','Unternehmenswebsites und Landingpages|Website-Relaunch|Layouts für Handy und Desktop|Leistungsseiten und Projektgalerien|Anfrageformulare und Kontaktlinks|Grundlegende Seitentitel und Suchmetadaten|Überarbeitung von Website-Inhalten|Optionale Website-Pflege und Updates'],
['Kurzvideoschnitt','Mehr aus deinem vorhandenen Videomaterial machen.','Reels, TikToks und YouTube Shorts|Schnitt von Werbevideos|Vertikale Videos bis 60 Sekunden|Untertitel und eingeblendete Texte|Grundlegende Audiobearbeitung|Musik mit passenden Nutzungsrechten|Vereinbarte Korrekturrunden|Einzelvideos oder monatliche Pakete'],
['Social-Media-Management','Regelmäßiger Content mit einem klaren Plan.','Monatliche Content-Planung|Grafiken und Texte|Kurzvideos in ausgewählten Paketen|Terminierung und Veröffentlichung|Anpassung an vereinbarte Plattformen|Monatlicher Leistungsbericht|Freigabe vor Veröffentlichung|Optionale Nachrichten- und Kommentarbetreuung']]
},
'it': {
'title':'Web design, montaggio video e gestione dei social media','meta':'Fame Agents crea siti web, monta video brevi e gestisce contenuti social. Base nell’UE, attività internazionale. Richiedi un preventivo personalizzato.',
'hero':['SITI WEB.','CONTENUTI.'],'intro':'La tua attività, presentata con chiarezza. I tuoi contenuti, pubblicati con costanza.',
'lead':'Web design, montaggio di video brevi e gestione dei social media per aziende che vogliono una presenza professionale online. Un partner, dal primo brief al supporto continuativo.',
'start':'Richiedi un preventivo','disciplines':'WEB DESIGN · MONTAGGIO VIDEO · SOCIAL MEDIA',
'services':'Tre servizi.\nUn partner.','serviceintro':'Crea il tuo sito. Monta i tuoi video. Mantieni attivi i tuoi social. Scegli un progetto o un supporto mensile.',
'abouttext':'Fame Agents aiuta le aziende a presentare i propri servizi con chiarezza online. Colleghiamo web design, montaggio video e contenuti social in un servizio coordinato. Altri servizi creativi sono disponibili su richiesta.',
'worldtext':'Abbiamo base nell’UE e lavoriamo con aziende in tutto il mondo. Pubblico, lingua, ambito e modalità di consegna guidano il progetto.',
'contacttext':'Raccontaci della tua attività e delle tue esigenze. Prepara un brief o parla con noi su WhatsApp. Definiremo l’ambito e prepareremo un preventivo personalizzato.',
'footer':'Siti web. Video. Social media.','budgetoptions':['Parliamone','Ho un budget definito','Ho bisogno di consigli sull’ambito'],
'whatsapp':'Scrivici su WhatsApp','share':'Apri WhatsApp con il mio brief',
'faqs':[['Posso prenotare un solo servizio?','Sì. Scegli un sito web, un pacchetto di montaggio video o la gestione dei social. Possiamo anche collegarli in un piano.'],['Come ottengo un preventivo?','Invia il brief o contattaci su WhatsApp. Concordiamo risultati, revisioni, tempi e costi prima di iniziare. Pubblicità, strumenti a pagamento e altri costi esterni sono indicati separatamente.'],['Realizzate le riprese?','Il montaggio usa il materiale che fornisci. Riprese, fotografia e animazione complessa possono essere quotate separatamente.'],['Cosa include la gestione dei social?','Pianificazione, grafiche, testi, programmazione, pubblicazione e rapporto mensile secondo il pacchetto. Risposte quotidiane, moderazione e pubblicità a pagamento sono servizi aggiuntivi.'],['Lavorate a livello internazionale?','Sì. Lavoriamo con aziende in tutto il mondo. Lingue del sito e dei contenuti e modalità di consegna vengono concordate per ogni progetto.'],['Dove posso vedere i vostri lavori?','Esplora i nostri canali pubblici o richiedi esempi pertinenti. Parleremo di lavori adatti alla tua attività.']],
'servicesData':[
['Web design e restyling','Spiega i servizi. Mostra i lavori. Facilita le richieste.','Siti aziendali e landing page|Restyling di siti web|Layout per mobile e computer|Pagine dei servizi e gallerie|Richieste di preventivo e link di contatto|Titoli e metadati di base per la ricerca|Revisione dei contenuti web|Manutenzione e aggiornamenti opzionali'],
['Montaggio di video brevi','Valorizza i video che hai già.','Reels, TikToks e YouTube Shorts|Montaggio di video promozionali|Video verticali fino a 60 secondi|Sottotitoli e testi sullo schermo|Pulizia audio di base|Musica con diritti d’uso adeguati|Revisioni concordate|Video singoli o pacchetti mensili'],
['Gestione dei social media','Contenuti costanti, con un piano chiaro.','Pianificazione mensile|Grafiche e testi|Video brevi in pacchetti selezionati|Programmazione e pubblicazione|Adattamento alle piattaforme concordate|Rapporto mensile sulle prestazioni|Approvazione prima della pubblicazione|Gestione opzionale di messaggi e commenti']]
}
}

def apply_focus(copy, services):
    for language, values in CONTENT.items():
        copy[language].update({k:v for k,v in values.items() if k!='servicesData'})
        services[language]=values['servicesData']
